name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Install rvm
      run: sudo apt-get install gnupg2 -y && gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB 
    - name: add rvm
      run:  curl -sSL https://get.rvm.io | bash -s stable
    - name: Set build script
      run: chmod +x ./build.sh
    - name: Build code
      run: ./build.sh
